import { useCallback, useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Link from 'next/link'

export default function Product() {
  const router = useRouter()
  const [product, setProduct] = useState(null)

  const loadProduct = useCallback(async () => {
    if (!router.query.id) {
      return
    }

    const resp = await fetch('https://database.shop.informatik.sexy/products/' + router.query.id)
    const data = await resp.json()
    setProduct(data)
  }, [router])

  const addToCart = useCallback(async () => {
    const id = router.query.id

    if (localStorage.cart) {
      localStorage.cart += ',' + id
    } else {
      localStorage.cart = id
    }

    router.push('/cart')
  }, [router])

  useEffect(() => {
    loadProduct()
  }, [loadProduct])

  return (
    <div>
      <Head>
        <title>Webshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/">
        <a>
          <h1>
            &lt; 🛍️ Webshop
          </h1>
        </a>
      </Link>

      <main>
        <h2>
          {product?.name}
        </h2>

        <p>
          {product?.description}
        </p>

        <p>
          Bewertung: {'⭐'.repeat(product?.rating)}
        </p>

        <p>
          Preis: {product?.price.toFixed(2)} €
        </p>

        <button onClick={() => addToCart()}>Zum Warenkorb hinzufügen</button>
      </main>
    </div>
  )
}
