import { useCallback, useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import ProductPreview from '../components/product-preview'

export default function Cart() {
  const [products, setProducts] = useState([])
  const [coupon, setCoupon] = useState("")

  async function loadProducts () {
    if (!localStorage.cart) {
      return
    }

    const ids = localStorage.cart.split(',')
    const products = []
    for (const id of ids) {
      const resp = await fetch('https://database.shop.informatik.sexy/products/' + id)
      const data = await resp.json()
      products.push(data)
    }

    setProducts(products)
  }

  useEffect(() => {
    loadProducts()
  }, [])

  const clearCart = useCallback(() => {
    localStorage.cart = ''
    setProducts([])
  }, [])

  return (
    <div>
      <Head>
        <title>Webshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/">
          <a>
            <h1>
              &lt; 🛍️ Webshop
            </h1>
          </a>
        </Link>

        <h2>
          Warenkorb ({products.length} Elemente)
        </h2>

        <div>
          {products.map((product, idx) => <ProductPreview key={idx} product={product} />)}
        </div>

        <p>
          <button onClick={() => clearCart()}>🗑️ Warenkorb leeren</button>
        </p>

        <p>
          Gutscheincode: <input type="text" value={coupon} onChange={e => setCoupon(e.target.value)} /> <br />
          Gutscheincode {coupon == 'abc123' ? 'gültig' : 'falsch'}
        </p>
      </main>
    </div>
  )
}
